### ISSUE TITLE
sdl error on rpi4

### ISSUE THREAD

**Issue by Askmewho** [ptitSeb/Serious-Engine#14]
STUBBED: load window icon in /home/pi/Desktop/ptit/Serious-Engine/Sources/SeriousSam/MainWindow.cpp, line 168.
STUBBED: Need SDL invisible window or something in /home/pi/Desktop/ptit/Serious-Engine/Sources/SeriousSam/MainWindow.cpp, line 327.

@ptitSeb Ive tried rc gordon (which its the one ive tried successfully on rpi3) repo too, but it fail on cpu detection function so ive copy you cpu detection function and it later fails on some sdl keyboard stuff

**Comment by ptitSeb** [comment]
My version should work on RPi. I have already seen success at runing it on an Rpi2.
The "STUBBED" message are ok, there are many in the code. What you should be sure of is that you build with "RelWithDebInfo" for cmake build type. Don't use Debug or no profile, because the (many) asserts will stop the program.

**Comment by Askmewho** [comment]
I've been using Release, but ive tried RelWithDebInfo and its causing the same, same output.

**Comment by ptitSeb** [comment]
On ARM, you can enabled ASM, there are some support, or left it disabled, there is C fallback for everything.

Which SeriousSam did you built, First or Second encounter? And are you sure all data are in correct places (or binary in correct place)

The 2 "STUBBED" lines are the only thing you get when you launch it?

(to my knowledge, icculus fork doesn't build for now, how did you made it buid?)

**Comment by Askmewho** [comment]
I dont know, ive compiled the game a long time ago! 

now it works, just a mistake (my one, like ever hahahah) 
but it crash on 64 bit arm.

Not 64-bit clean in /home/pi/Escritorio/Serious-Engine/Sources/EntitiesMP/Player.es, line 6561.

but I will check it on raspbian 32 bit. thanks ptit. I will close this when get it working on raspbian and post here the link to my video about your game fork!

**Comment by Askmewho** [comment]
@ptitSeb  here it is! https://www.youtube.com/watch?v=hMEq8DCZbBA&feature=youtu.be

ive forget again to mention you on the video! sorry, so I add that on the desc.
