### ISSUE TITLE
Segmentation fault (Linux 64)

### ISSUE THREAD

**Issue by nesper8** [ptitSeb/Serious-Engine#20]
![Screenshot_2020-08-25_14-25-25](https://user-images.githubusercontent.com/57890520/91154311-025d8400-e6df-11ea-9ff7-f52679439b6f.png)
Got successfully compiled tho

**Comment by nesper8** [comment]
Fixed by copying the SE1_10.gro to the game root folder
Launches and shows video but crashes

[nep@naveen-hpnotebook Bin]$ ./ssam-tfe 
STUBBED: load window icon in /home/nep/Projects/Serious-Engine/Sources/SeriousSam/MainWindow.cpp, line 168.
STUBBED: Need SDL invisible window or something in /home/nep/Projects/Serious-Engine/Sources/SeriousSam/MainWindow.cpp, line 327.
STUBBED: !!! FIXME: get the code back in from Ryan's original port. in /home/nep/Projects/Serious-Engine/Sources/Engine/Base/Stream.cpp, line 921.
STUBBED: Report actual SDL device name? in /home/nep/Projects/Serious-Engine/Sources/Engine/Sound/SoundLibrary.cpp, line 269.
STUBBED: co-opt the existing T-buffer support for multisampling? in /home/nep/Projects/Serious-Engine/Sources/Engine/Graphics/SDL/SDLOpenGL.cpp, line 113.
STUBBED: this can't possibly be right, yeah? in /home/nep/Projects/Serious-Engine/Sources/Engine/Base/SDL/SDLEvents.cpp, line 147.
STUBBED: SDL2 can handle these events in /home/nep/Projects/Serious-Engine/Sources/SeriousSam/SeriousSam.cpp, line 1027.
Segmentation fault (core dumped)
[nep@naveen-hpnotebook Bin]$ ./ssam-tfe

**Comment by LibreHacker** [comment]
STUBBED: Not 64-bit clean in Serious-Engine-master/Sources/EntitiesMP/Player.es, line 6561.
Segmentation fault

**Comment by ptitSeb** [comment]
The STUBBED mesage can be ignored for now.

But all those "bug repport" lacks details: what distrib, what build, what bitness. and also, how did you instal the data or how did you inject the new binary in the windows folder?
