### ISSUE TITLE
Can not run the game

### ISSUE THREAD

**Issue by mad-student** [ptitSeb/Serious-Engine#4]
When I try to run game i get this:
STUBBED: load window icon in /home/psycho/games/Serious-Engine/Sources/SeriousSam/MainWindow.cpp, line 168.
STUBBED: Need SDL invisible window or something in /home/psycho/games/Serious-Engine/Sources/SeriousSam/MainWindow.cpp, line 327.
And game won't start. Is there any fix for that. And I sorry that I so annoying.
What is interesting? It occurred even when I deleted MainWindow.cpp.
[MainWindow.cpp.tar.gz](https://github.com/ptitSeb/Serious-Engine/files/2087122/MainWindow.cpp.tar.gz)

**Comment by ptitSeb** [comment]
The STUB message are ok, and can be safely ignored.

The main binary and .so built be the make need to be copied in the `Bin` folder of the game, and lauched as `Bin/ssam-tfe`
So to recp, in Bin, for the 1st encounter, you should have `libEntities.so`, `libGame.so`, `libShaders.so` and `ssam-tfe`

**Comment by ptitSeb** [comment]
You are using Steam version ? Then music doesn't use amp11lib, but vorbis.
One thing not to forget is to copy `SE1_10.gro` from this repo in the game folder, along with the other .gro files (I know I have to write a "howto" for this).

**Comment by ptitSeb** [comment]
Also, If you had started be builder The Second Encounter and then built First Encounter, be sure to clean your build folder (or use different build folder), or you will experience issue similar to what you described.

**Comment by mad-student** [comment]
I builded TFE into separate directory but i try to remake it maybe it will help.

**Comment by mad-student** [comment]
I rebuild 1st encounter and place binaries into game directory that I downloaded from Steam (in first time i copied *.gro files from 1st & 2nd encounter into repo directory). Also music was my fault - I forgot to install libvorbis-dev. Now all works pretty fine. Thanks again for a lot of help and sorry for time, that I take from You.

**Comment by ptitSeb** [comment]
Glad it works :)

Enjoy this very good game!
