### ISSUE TITLE
Tremor sound offsets bug

### ISSUE THREAD

**Issue by Skyrimus** [ptitSeb/Serious-Engine#45]
If using tremor like vorbis codec in TFE it getting Bug warning anytime if any sounds playing

SoundObject.cpp
CSoundObject::SetOffset void

Line 325
  ASSERT( fOffset>=0);
  if( fOffset<0) {
    CPrintF( "BUG: Trying to set negative offset (%.2g) in sound '%s' !\n", fOffset, (const char *) (CTString&)psoTail->so_pCsdLink->GetName());
    fOffset = 0.0f;
  }

**Comment by ptitSeb** [comment]
Why did you closed it?
