### ISSUE TITLE
confif folder paths

### ISSUE THREAD

**Issue by Askmewho** [ptitSeb/Serious-Engine#5]
Hi Ptit! sorry for this silly question, but ssam always runs as first time with default config on my pi, could you tell me where i can create a config file to avoid this? 

check the performance I achieve :
https://www.youtube.com/watch?v=9-Vb8VS-zEM

really good!!

**Comment by ptitSeb** [comment]
Nice performances indeed!

For config file, take a look at the log: ` ~/.serious/serioussamse/ssam.log` you should see inside what file it look for...

**Comment by Askmewho** [comment]
Thanks!

**Comment by Askmewho** [comment]
It doesnt create any log. I run it directly from the build folder. Doesnt creat any .serious folder too.. Mmm... Whit which parameter i need to compile it to achieve that?

**Comment by ptitSeb** [comment]
Pref folder is computed in `Serious-Engine/Sources/Engine/Base/Unix/UnixFileSystem.cpp` line 81 (using `SDL_GetPrefPath(...)`). Folder should be something like `~/Serious Engine/seriousesamse` (previous folder was from an old version, sorry).

**Comment by Askmewho** [comment]
Well this its getting weird... Maybe I compiled another repo... But they are the same on many ways.... I will figured out. But something its wrong... Thanks petit. I compiled this, i think, long mounths ago. And then then the new mesa give me some extrampower than i never think... I just recompiled it. The performance its awesome... Just I pray for some request i made to the mesa dev of vc4... When you have so amount of support in mesa drivers you can achieve anything... Well. Dont close this. I will report any news

**Comment by Askmewho** [comment]
Its a shame than pandora never get its upgrade... I was a really good concept. What notaz didi for arm its just... I cant describe it with words... It took me 2 mounths tes his commits on wine... But i get diablo Ii on the pi thanks tom him. I am an historian...milesnaway from programing. Its passion whats motive me... And it will be. Sorry... I am a little dru343k right now hahahaha

**Comment by Askmewho** [comment]
Thanks to rpi i can manega a lot of thing on github ir linux... I feel... Withnsome kind of power than no x86 platform could give me right now. The n2 odroid will be another gate to me like thenpi3 was... This its my linux story. I hope you like it.

**Comment by Askmewho** [comment]
Belive me. Any notaz commit cost me 5 hours mof compiling. I barely know whatmi were doing. Just test every commit one by one. A shame was than some youtube usser acussed me to stealth notaz effort. I just did wat i could. I spend 2 mpounths on get a good wine for running notaz binaries and because some confusing chatmwith eta he doesnt understood that the all thing was done by notaz. Meanwhile, i did it for the rpi community. I did it because we love arm cheap devices. Sorry for this message. But I need to release this kind of story. My english its not the best. I do what i can. My channel its in english. Not because i could get more subs with that, just because we ar a comunnity. An the world speek english.

**Comment by Askmewho** [comment]
Sorry for the writhing.... Its not just my english... I am on a tablet too... Hahhaa

**Comment by Askmewho** [comment]
I am soo sorry for my last comments.... beer situation.

I found the log, it says...

Cannot load variable from 'DefaultMod.txt':
Cannot open file `/home/pi/.Serious-Engine/DefaultMod.txt' (No such file or directory) ()

I understand than defaultmod.txt its the default config file. and it never create one. could i add a custom one?

**Comment by ptitSeb** [comment]
The `DefaultMod.txt` should be present in the data. If not, you can find a copy in the repo itself, in the root folder.

**Comment by Askmewho** [comment]
Ok. I will use the repo one. Thanks! Closing
