### ISSUE TITLE
Cutscenes Broken Using TFE

### ISSUE THREAD

**Issue by act17** [ptitSeb/Serious-Engine#50]
Any and all scripted events play from the first person, as in from Sam's physical location within the game world. For example, the intro cutscene where Sam fires a minigun, I am currently playing as Sam holding a minigun. I cannot control the game, besides press Esc. and load into the menu.
When trying to start a new game, the first cutscene plays with the regular game's HUD - with the Colt Pistol out as well - as opposed to it being blank so that the game can display the introducing flavour text. I cannot control the game in any capacity, except for the aforementioned ability to get into the menu. This means I can't even skip the cutscene, and get into gameplay.

I compiled this on Ubuntu 20.04 64-Bit using the --recurse-submodules parameter in Git, because without that command being added, the building process would fail.

**Comment by ptitSeb** [comment]
There is no submodule in this repo, `--recurse-submodules` will have no effect. Did you put the data correctly? And you are sure you built The First Encounter? (also ModEXT.txt needs to be removed for TFE).

**Comment by act17** [comment]
I did. I passed the flag required to build, and it built _ssam-tfe_. I also redownloaded the source code without the `--recurse-submodules` flag. Same error.

**Comment by ptitSeb** [comment]
For the `--recurse-submodules`, I'm pretty sure the issue is just that you use `make -j 2` or something like that and it fails the 1st tie, then succeed the 2nd time, just because it's the second time.

For TFE, the `.gro` files that should be present are:
```
-rwxr--r--  1 seb seb 201152043 Feb  6  2016 1_00c.gro
-rwxr--r--  1 seb seb     17995 Feb  6  2016 1_00c_Logo.gro
-rwxr--r--  1 seb seb     10859 Feb  6  2016 1_00c_scripts.gro
-rwxr--r--  1 seb seb   1199329 Feb  6  2016 1_00_ExtraTools.gro
-rwxr--r--  1 seb seb  71825740 Feb  6  2016 1_00_music.gro
-rwxr--r--  1 seb seb     23553 Feb  6  2016 1_04_patch.gro
-rwxr--r--  1 seb seb   5419415 Apr 10  2016 SE1_minimum.gro
```

**Comment by act17** [comment]
What's `SE1_minimum.gro`?

**Comment by act17** [comment]
As it turns out, I was very, very, very dumb. I failed to copy the actual files from `cmake-build/Debug`, proceeding to mode them into the `Bin/` folder of my Serious Sam directory, alongside the entirety of the `Ecc/` folder.
Sorry for wasting time man.

But, while I have the oppertunity, would you happen to know a console command that can increase the FPS limit from 60 to any integer I assume? And alongside that, is the Mac-Arm Build Shell also able to work on Raspberry Pis thanks to their chipset? Or should I simply use the Linux Build Shell for a Raspberry Pi?
Thanks in advance.
