### ISSUE TITLE
Compiling and Running WorldEditor

### ISSUE THREAD

**Issue by act17** [ptitSeb/Serious-Engine#53]
I apologize for the very dumb question, but how would I go about compiling WorldEditor so that I can make my own levels? Thanks in advance.

**Comment by ptitSeb** [comment]
WorldEditor cannot be build on Linux. It's a windows only program for now, sorry.

**Comment by act17** [comment]
Oh, thanks for telling me and thanks for your time. I'll see if I can jerryrig it with Wine.
