### ISSUE TITLE
Issues in some source files that cause build errors

### ISSUE THREAD

**Issue by gipi942** [ptitSeb/Serious-Engine#55]
There are two issues that occurred to me while I tried to compile, and none of the fixes present in the Issues here solved them. I used the `cmake -DCMAKE_BUILD_TYPE=Release ..` (similar to [this](https://github.com/ptitSeb/Serious-Engine/issues/3#issuecomment-395969879)) First one reports an error in Sources/Engine/Engine.cpp (on like 131), the `#if` doesn't appear to have a proper `#endif`. Adding one a few lines below can solve the build issue. Second one occurs in Engine/SDL/Base/SDLInput.cpp (on line 727) and concerns an imporoperly declared variable. The build part can be fixed by simply adding the missing part (instead of `unsigned ...` you'll put `const unsigned ...`). Build issues will be gone (provided one applies other fixes, like installing libogg-dev, copies files, etc.)
Just thought I'd add this for others to know.

**Comment by ptitSeb** [comment]
Are you sure you are taking about the sources on my repo and not the sources on icculus one instead?
The `#if` in line `132` of `Sources/Engine/Engine.cpp` is ended with an `#endif` line `180`, with an `#elif` line `146`

**Comment by gipi942** [comment]
Upon further inspection, it appears to be neither, because I mistakenly cloned rcgordon's repo (because that's the one in the readme)
Sorry for wasting your time mate
